; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:m5stack-cores3]
platform = espressif32
board = m5stack-cores3
framework = arduino
monitor_speed = 115200
build_flags =
    -DCARDGFX_USE_PSRAM=0
    -DARDUINO_LOOP_STACK_SIZE=16384
    -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
	m5stack/M5Unified@^0.2.10
	m5stack/M5Cardputer@^1.1.1
	m5stack/M5GFX@^0.2.16
	rweather/Crypto@^0.4.0
